/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author sam
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pan_slide = new javax.swing.JPanel();
        lbl_slide = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_set = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbl_user = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        pan_form = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txt_url = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_reg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_pass1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pan_tab = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tb_mostrar = new javax.swing.JTable();
        txt_femail = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_fusername = new javax.swing.JTextField();
        lbl_press = new javax.swing.JLabel();
        txt_fpass = new javax.swing.JPasswordField();
        btn_mod = new javax.swing.JButton();
        lbl_user_id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_nota = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        pan_sup = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_slide.setBackground(new java.awt.Color(17, 138, 178));
        pan_slide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_slide.setBackground(new java.awt.Color(255, 32, 0));
        lbl_slide.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        lbl_slide.setForeground(new java.awt.Color(254, 254, 254));
        lbl_slide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_slide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu2.png"))); // NOI18N
        lbl_slide.setToolTipText("presiona para empujar");
        lbl_slide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pan_slide.add(lbl_slide, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 25, 25));

        btn_add.setBackground(new java.awt.Color(7, 59, 76));
        btn_add.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        btn_add.setForeground(new java.awt.Color(254, 254, 254));
        btn_add.setText("Añadir");
        btn_add.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setFocusPainted(false);
        pan_slide.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 50));

        btn_set.setBackground(btn_add.getBackground());
        btn_set.setFont(btn_add.getFont());
        btn_set.setForeground(new java.awt.Color(254, 254, 254));
        btn_set.setText("Ajustes");
        btn_set.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        btn_set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_set.setFocusPainted(false);
        pan_slide.add(btn_set, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        btn_ver.setBackground(new java.awt.Color(7, 59, 76));
        btn_ver.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        btn_ver.setForeground(new java.awt.Color(254, 254, 254));
        btn_ver.setText("Guardados");
        btn_ver.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        btn_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ver.setFocusPainted(false);
        pan_slide.add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 50));

        jButton4.setBackground(btn_add.getBackground());
        jButton4.setFont(btn_add.getFont());
        jButton4.setForeground(btn_add.getForeground());
        jButton4.setText("Logs");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        pan_slide.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 50));

        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        pan_slide.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 80));

        lbl_username.setForeground(new java.awt.Color(254, 254, 254));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pan_slide.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 140, 140, 30));

        jPanel1.add(pan_slide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 550));
        pan_slide.getAccessibleContext().setAccessibleName("");

        pan_form.setBackground(new java.awt.Color(254, 254, 254));
        pan_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator1.setOpaque(true);
        pan_form.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 290, 2));

        jSeparator2.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator2.setOpaque(true);
        pan_form.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 2));

        jSeparator3.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator3.setOpaque(true);
        pan_form.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 290, 2));

        jSeparator4.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator4.setOpaque(true);
        pan_form.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 290, 2));

        jSeparator5.setBackground(new java.awt.Color(1, 1, 1));
        jSeparator5.setOpaque(true);
        pan_form.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 290, 2));

        jLabel1.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 13)); // NOI18N
        jLabel1.setText("Confirmar Password");
        pan_form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 30));

        txt_url.setBorder(null);
        txt_url.setOpaque(false);
        pan_form.add(txt_url, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 290, 40));

        txt_username.setBorder(null);
        txt_username.setOpaque(false);
        pan_form.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 290, 40));

        txt_email.setBorder(null);
        txt_email.setOpaque(false);
        pan_form.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 290, 40));

        jLabel2.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 13)); // NOI18N
        jLabel2.setText("Nombre de Sitio");
        pan_form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 13)); // NOI18N
        jLabel3.setText("Nombre de Usuario");
        pan_form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 13)); // NOI18N
        jLabel4.setText("Email");
        pan_form.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txt_pass.setBorder(null);
        txt_pass.setOpaque(false);
        pan_form.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 290, 40));

        btn_reg.setBackground(new java.awt.Color(17, 138, 178));
        btn_reg.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 14)); // NOI18N
        btn_reg.setForeground(new java.awt.Color(254, 254, 254));
        btn_reg.setText("Registrar");
        pan_form.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, 40));

        jLabel10.setFont(new java.awt.Font("Expansiva", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registro de Nuevo Perfil");
        pan_form.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 260, 30));

        txt_pass1.setBorder(null);
        txt_pass1.setOpaque(false);
        pan_form.add(txt_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 290, 40));

        jLabel11.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 13)); // NOI18N
        jLabel11.setText("Password");
        pan_form.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Expansiva", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Registro de Nuevo Perfil");
        pan_form.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 260, 30));

        jPanel1.add(pan_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 600, 520));

        pan_tab.setBackground(new java.awt.Color(254, 254, 254));
        pan_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(254, 254, 254));

        tb_mostrar.setBackground(new java.awt.Color(254, 254, 254));
        tb_mostrar.setFont(new java.awt.Font("Michroma", 1, 12)); // NOI18N
        tb_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "user_id", "web_id", "URL", "Nombre", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_mostrar.setSelectionBackground(new java.awt.Color(7, 59, 76));
        tb_mostrar.setSelectionForeground(new java.awt.Color(254, 254, 254));
        tb_mostrar.setShowVerticalLines(false);
        tb_mostrar.getTableHeader().setReorderingAllowed(false);
        scroll.setViewportView(tb_mostrar);
        if (tb_mostrar.getColumnModel().getColumnCount() > 0) {
            tb_mostrar.getColumnModel().getColumn(0).setResizable(false);
            tb_mostrar.getColumnModel().getColumn(1).setResizable(false);
            tb_mostrar.getColumnModel().getColumn(2).setResizable(false);
            tb_mostrar.getColumnModel().getColumn(3).setResizable(false);
            tb_mostrar.getColumnModel().getColumn(4).setResizable(false);
            tb_mostrar.getColumnModel().getColumn(5).setResizable(false);
        }

        pan_tab.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 170));

        txt_femail.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        txt_femail.setForeground(new java.awt.Color(1, 1, 1));
        txt_femail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_femail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_femail.setOpaque(false);
        pan_tab.add(txt_femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 210, 40));

        txt_fname.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(1, 1, 1));
        txt_fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_fname.setOpaque(false);
        pan_tab.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, 40));

        txt_fusername.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        txt_fusername.setForeground(new java.awt.Color(1, 1, 1));
        txt_fusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fusername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_fusername.setOpaque(false);
        pan_tab.add(txt_fusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 210, 40));

        lbl_press.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl_press.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_press.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show password.png"))); // NOI18N
        pan_tab.add(lbl_press, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 30, 40));

        txt_fpass.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        txt_fpass.setForeground(new java.awt.Color(1, 1, 1));
        txt_fpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_fpass.setOpaque(false);
        pan_tab.add(txt_fpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 210, 40));

        btn_mod.setBackground(new java.awt.Color(17, 138, 178));
        btn_mod.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 14)); // NOI18N
        btn_mod.setForeground(new java.awt.Color(254, 254, 254));
        btn_mod.setText("Modificar");
        btn_mod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btn_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mod.setRequestFocusEnabled(false);
        pan_tab.add(btn_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 100, 40));

        lbl_user_id.setOpaque(true);
        pan_tab.add(lbl_user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 40, 40));

        jLabel5.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(7, 59, 76));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        pan_tab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 250, 30));

        jLabel6.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 59, 76));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre del Sitio");
        pan_tab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, 30));

        jLabel7.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(7, 59, 76));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre de Usuario");
        pan_tab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 250, 30));

        jLabel8.setFont(new java.awt.Font("Carlito", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 59, 76));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Correo");
        pan_tab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 250, 30));

        btn_del.setBackground(new java.awt.Color(183, 22, 32));
        btn_del.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 14)); // NOI18N
        btn_del.setForeground(new java.awt.Color(254, 254, 254));
        btn_del.setText("Eliminar");
        btn_del.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btn_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_del.setRequestFocusEnabled(false);
        pan_tab.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 100, 40));

        txa_nota.setColumns(20);
        txa_nota.setRows(5);
        jScrollPane1.setViewportView(txa_nota);

        pan_tab.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 300, -1));

        jLabel9.setFont(jLabel6.getFont());
        jLabel9.setForeground(jLabel6.getForeground());
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nota:");
        pan_tab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 40, 40));

        jPanel1.add(pan_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 600));

        pan_sup.setBackground(new java.awt.Color(17, 138, 178));
        jPanel1.add(pan_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_add;
    public javax.swing.JButton btn_del;
    public javax.swing.JButton btn_mod;
    public javax.swing.JButton btn_reg;
    public javax.swing.JButton btn_set;
    public javax.swing.JButton btn_ver;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel lbl_press;
    public javax.swing.JLabel lbl_slide;
    public javax.swing.JLabel lbl_user;
    public javax.swing.JLabel lbl_user_id;
    public javax.swing.JLabel lbl_username;
    public javax.swing.JPanel pan_form;
    public javax.swing.JPanel pan_slide;
    private javax.swing.JPanel pan_sup;
    public javax.swing.JPanel pan_tab;
    public javax.swing.JScrollPane scroll;
    public javax.swing.JTable tb_mostrar;
    public javax.swing.JTextArea txa_nota;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_femail;
    public javax.swing.JTextField txt_fname;
    public javax.swing.JPasswordField txt_fpass;
    public javax.swing.JTextField txt_fusername;
    public javax.swing.JPasswordField txt_pass;
    public javax.swing.JPasswordField txt_pass1;
    public javax.swing.JTextField txt_url;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
