/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author sam
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_reg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_passconf = new javax.swing.JPasswordField();
        txt_passreg = new javax.swing.JPasswordField();
        txt_nreg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_reg.setBackground(new java.awt.Color(254, 254, 254));
        pan_reg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lato Heavy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Nuevo Usuario de Sistema");
        pan_reg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 410, 40));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        pan_reg.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, 40));
        pan_reg.add(txt_passconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 230, 40));
        pan_reg.add(txt_passreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, 40));

        txt_nreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nregActionPerformed(evt);
            }
        });
        pan_reg.add(txt_nreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 230, 40));

        jLabel2.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel2.setText("Confirmar Password");
        pan_reg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 140, 30));

        jLabel3.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel3.setText("Nombre de Usuario");
        pan_reg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 100, 130, 30));

        jLabel4.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel4.setText("Correo");
        pan_reg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 30));

        jLabel5.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel5.setText("Password");
        pan_reg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 30));

        btn_reg.setBackground(new java.awt.Color(33, 23, 192));
        btn_reg.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        btn_reg.setForeground(new java.awt.Color(254, 254, 254));
        btn_reg.setText("Registrar");
        pan_reg.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 110, 40));

        jPanel1.setBackground(new java.awt.Color(33, 23, 192));
        jPanel1.setForeground(new java.awt.Color(33, 23, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pan_reg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        getContentPane().add(pan_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nregActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pan_reg;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_nreg;
    public javax.swing.JPasswordField txt_passconf;
    public javax.swing.JPasswordField txt_passreg;
    // End of variables declaration//GEN-END:variables
}
