/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author sam
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_reg = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        txt_passconf = new javax.swing.JPasswordField();
        txt_passreg = new javax.swing.JPasswordField();
        txt_nreg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_alert = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        lbl_okay = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_closereg = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 530));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_reg.setBackground(new java.awt.Color(254, 254, 254));
        pan_reg.setPreferredSize(new java.awt.Dimension(600, 530));
        pan_reg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_email.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_email.setOpaque(false);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        pan_reg.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 260, 40));

        txt_passconf.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_passconf.setOpaque(false);
        pan_reg.add(txt_passconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 260, 40));

        txt_passreg.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_passreg.setOpaque(false);
        pan_reg.add(txt_passreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 260, 40));

        txt_nreg.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_nreg.setOpaque(false);
        txt_nreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nregActionPerformed(evt);
            }
        });
        pan_reg.add(txt_nreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 260, 40));

        jLabel2.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Confirmar Password");
        pan_reg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, 30));

        jLabel3.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre de Usuario");
        pan_reg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 30));

        jLabel4.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Correo");
        pan_reg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 30));

        jLabel5.setFont(new java.awt.Font("Lato", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        pan_reg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        lbl_alert.setFont(new java.awt.Font("Cantarell", 3, 12)); // NOI18N
        lbl_alert.setForeground(new java.awt.Color(226, 42, 35));
        lbl_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pan_reg.add(lbl_alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 40));

        btn_reg.setBackground(new java.awt.Color(17, 138, 178));
        btn_reg.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        btn_reg.setForeground(new java.awt.Color(254, 254, 254));
        btn_reg.setText("Registrar");
        pan_reg.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));
        pan_reg.add(lbl_okay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 30, 30));

        jPanel1.setBackground(new java.awt.Color(17, 138, 178));
        jPanel1.setForeground(new java.awt.Color(33, 23, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_closereg.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 24)); // NOI18N
        lbl_closereg.setForeground(new java.awt.Color(254, 254, 254));
        lbl_closereg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_closereg.setText("X");
        lbl_closereg.setToolTipText("cerrar");
        lbl_closereg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lbl_closereg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        pan_reg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        btn_cancel.setBackground(new java.awt.Color(192, 46, 58));
        btn_cancel.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(254, 254, 254));
        btn_cancel.setText("Cancelar");
        pan_reg.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 110, 40));

        getContentPane().add(pan_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nregActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancel;
    public javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_alert;
    public javax.swing.JLabel lbl_closereg;
    public javax.swing.JLabel lbl_okay;
    private javax.swing.JPanel pan_reg;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_nreg;
    public javax.swing.JPasswordField txt_passconf;
    public javax.swing.JPasswordField txt_passreg;
    // End of variables declaration//GEN-END:variables
}
